# Generated by Django 3.1.3 on 2020-12-01 04:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('elev', models.PositiveSmallIntegerField(blank=True, verbose_name='elevation')),
                ('pgm', models.CharField(max_length=50)),
                ('buoy_type', models.CharField(max_length=10)),
                ('met', models.CharField(default='n', max_length=1)),
                ('currents', models.CharField(default='n', max_length=1)),
                ('waterquality', models.CharField(default='n', max_length=1)),
                ('dart', models.CharField(default='n', max_length=1)),
                ('seq', models.PositiveSmallIntegerField(blank=True, verbose_name='seq attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buoyant.buoy')),
            ],
        ),
    ]
