# Generated by Django 3.1.3 on 2020-12-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoyant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoy',
            name='elev',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='elevation'),
        ),
        migrations.AlterField(
            model_name='buoy',
            name='seq',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='seq attribute'),
        ),
    ]
