# Generated by Django 3.1.3 on 2021-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoyant', '0004_auto_20210130_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorological',
            name='wave_dir',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meteorological',
            name='wind_dir',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
